### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by cssxsh** [project-mirai/mirai-silk-converter#4]
原 issue https://github.com/project-mirai/mirai-api-http/issues/690

https://sayashi-vits-uma-genshin-honkai.hf.space/file=/tmp/tmpk13nrb_w/tmpujff2_ce.wav

debug info: 
```
ffmpeg version 5.1-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'test\123.wav':
  Duration: 00:00:01.94, bitrate: 352 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, mono, s16, 352 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, s16le, to 'pipe:':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: pcm_s16le, 22050 Hz, mono, s16, 352 kb/s
###HZ: 22050
io.github.kasukusakura.silkcodec.CoderException: SKP_Silk_Encode returned -2
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(Native Method)
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(SilkCoder.java:46)
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(SilkCoder.java:36)
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(SilkCoder.java:63)
	at io.github.kasukusakura.silkcodec.AudioToSilkCoder.connect(AudioToSilkCoder.java:98)
	at io.github.kasukusakura.silkcodec.AudioToSilkCoder.connect(AudioToSilkCoder.java:25)
	at net.mamoe.mirai.silkconverter.Data.convert0(SilkConverter.kt:46)
	at net.mamoe.mirai.silkconverter.SilkConverterImpl$convert$2.invoke(SilkConverter.kt:62)
	at net.mamoe.mirai.silkconverter.SilkConverterImpl$convert$2.invoke(SilkConverter.kt:62)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    Metadata:
      encoder         : Lavc59.37.100 pcm_s16le
size=       4kB time=00:00:00.09 bitrate= 352.8kbits/s speed=9.29e+04x    
size=      84kB time=00:00:01.93 bitrate= 352.8kbits/s speed= 558x    
video:0kB audio:84kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
[AudioToSilkCoder] pcm completed
[SilkCoder] Encode: tx=1, strict=1, fs Hz=22050, max sample rate=24000, packet size=441, band-fec=0, DTX=0, complexity=2, bit-rate=24000
[SilkCoder] Writing TX Silk-v3 Header
[SilkCoder] Start....
```

Silk 只生成了一个文件头
![image](https://user-images.githubusercontent.com/32539286/220281455-411fbf0e-285e-4fd6-ac9e-1263f6045229.png)

**Comment by cssxsh** [comment]
https://github.com/KasukuSakura/silk-codec/pull/3

**Comment by cssxsh** [comment]
很奇怪 `22050Hz` 不能转码

话说有转码的Hz范围吗 @Karlatemp

**Comment by cssxsh** [comment]
临时修复版本 [mirai-silk-converter-0.0.6.mirai.jar](https://github.com/cssxsh/mirai-tts-plugin/releases/download/v1.1.1/mirai-silk-converter-0.0.6.mirai.jar)
